In [1]:
#Problem 1- Array Creation
#1
import numpy as np
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [2]:
#2
import numpy as np
a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#3
import numpy as np
a = np.full((2, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [4]:
#4
import numpy as np
a = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(a)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [5]:
#5
import numpy as np
a = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(a)
print(ones_like_array)

[[1 1]
 [1 1]]


In [6]:
#6
import numpy as np
new_list =[1, 2, 3, 4]
converted_array = np.array(new_list)
print(converted_array)

[1 2 3 4]


In [7]:
#Problem 2: Array Manipulation: Numerical Ranges and Array indexing
#1
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#2
import numpy as np
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#3
import numpy as np
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#4
import numpy as np
arr = np.random.random(30)
mean = arr.mean()
print(arr, mean)

[0.14462207 0.65742025 0.93359843 0.44839359 0.37858599 0.0593747
 0.9151795  0.80529461 0.50483686 0.63153007 0.36579387 0.52582325
 0.89314126 0.98009016 0.96014862 0.95930509 0.15150905 0.47399861
 0.19436794 0.03156964 0.27238843 0.56276548 0.27026933 0.77908746
 0.9292674  0.00219846 0.52287788 0.55099217 0.21071801 0.06188836] 0.5059012178369866
